Used dedicated library to parse arguments
Serwi/CS50 pull request #15
Opened 2021-03-23 16:21 UTC by Serwi

Used argparse library to parse arguments

2021-03-24 13:12 UTC, szefoski requested changes
"Update dna.py" is a bad commit title. Please check if you can ammend the commit.

2021-03-24 13:15 UTC, szefoski approved these changes, later dismissed

2021-03-24 13:45 UTC, Serwi commented
> 
> 
> "Update dna.py" is a bad commit title. Please check if you can amend the commit.
Can't amend pushed commit

2021-03-28 13:15 UTC, szefoski approved these changes

2021-03-28 18:20 UTC, merged